name: eslint
on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  run-eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: yarn
      - run: yarn ci
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v1
        with:
          report_paths: 'reports/eslint/*.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
