name: Sync git to drupal.org
on:
  push:
    branches:
      - 'main'
jobs:
  push-to-drupalorg:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DRUPAL_RG_KEY }}
        with:
          source-repo: git@github.com:jsdrupal/js-client.git
          destination-repo: git@git.drupal.org:sandbox/justafish-3186221.git


